"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { RotateCcw, Sparkles, Volume2, VolumeX } from "lucide-react";

const BASE = "/adjectivebloom";
const asset = (path: string) => `${BASE}${path}`;

const PAIRS = [
  ["confident", "shy"], ["reliable", "unreliable"], ["hard-working", "lazy"],
  ["enthusiastic", "unenthusiastic"], ["brave", "cowardly"], ["sensible", "careless"],
  ["calm", "angry"], ["positive", "negative"], ["generous", "ungenerous"],
  ["talented", "talentless"], ["sociable", "unsociable"], ["patient", "impatient"],
  ["curious", "uninterested"], ["creative", "uncreative"],
] as const;

function shuffled<T>(items: readonly T[]) { return [...items].sort(() => Math.random() - 0.5); }
const photoFor = (word: string) => asset(`/photos-webp/${word}.webp`);
function growthStageFor(n:number){if(n<=1)return 0;if(n===2)return 1;if(n===3)return 2;if(n<=5)return 3;if(n<=7)return 4;if(n<=9)return 5;if(n<=12)return 6;return 7;}

export default function Home() {
  const [screen,setScreen]=useState<"start"|"game"|"finish">("start"); const [round,setRound]=useState(0);
  const cards=useMemo(()=>shuffled(PAIRS.map(([a])=>a)),[round]); const [batchIndex,setBatchIndex]=useState(0);
  const activeCards=useMemo(()=>cards.slice(batchIndex*4,batchIndex*4+4),[cards,batchIndex]);
  const activeEnvelopes=useMemo(()=>shuffled(activeCards.map(w=>PAIRS.find(([a])=>a===w)?.[1]??"")),[activeCards]);
  const [selected,setSelected]=useState<string|null>(null),[dragging,setDragging]=useState<string|null>(null),[matched,setMatched]=useState<string[]>([]);
  const [streak,setStreak]=useState(0),[bestStreak,setBestStreak]=useState(0),[feedback,setFeedback]=useState("Pick up a Polaroid and find its opposite envelope");
  const [wrongEnvelope,setWrongEnvelope]=useState<string|null>(null); const [thread,setThread]=useState<{cursorX:number;cursorY:number;targetX:number;targetY:number}|null>(null);
  const [sound,setSound]=useState(true),[volume,setVolume]=useState(.38); const audioRef=useRef<AudioContext|null>(null),musicRef=useRef<HTMLAudioElement|null>(null);
  const growthStage=growthStageFor(matched.length);
  useEffect(()=>{[asset("/desk-background.webp"),asset("/envelope-fern-closed-opt.webp"),asset("/envelope-fern-open-opt.webp"),...Array.from({length:8},(_,i)=>asset(`/growth-stages/stage-${i}.webp`)),asset("/growth-stages/seed.webp")].forEach(src=>{const im=new Image();im.src=src});cards.slice(batchIndex*4,(batchIndex+2)*4).forEach(w=>{const im=new Image();im.src=photoFor(w)})},[cards,batchIndex]);
  const audio=()=>{if(!audioRef.current)audioRef.current=new AudioContext();if(audioRef.current.state==="suspended")void audioRef.current.resume();return audioRef.current};
  const tone=(f:number,d:number,l=.035,t:OscillatorType="sine",delay=0)=>{if(!sound)return;const c=audio(),o=c.createOscillator(),g=c.createGain();o.type=t;o.frequency.setValueAtTime(f,c.currentTime+delay);g.gain.setValueAtTime(l*volume,c.currentTime+delay);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+delay+d);o.connect(g).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+d)};
  const playSound=(k:"click"|"paper"|"seal"|"wrong"|"finish")=>{if(!sound)return;if(k==="click")tone(240,.045,.028,"square");if(k==="paper"){tone(620,.08,.018,"triangle");tone(760,.06,.012,"triangle",.035)}if(k==="seal"){tone(115,.12,.06);tone(360,.18,.025,"triangle",.07)}if(k==="wrong"){tone(145,.11,.04,"square");tone(110,.14,.035,"square",.1)}if(k==="finish")[523,659,784,1047].forEach((f,i)=>tone(f,.42,.035,"sine",i*.13))};
  const stopMusic=(r=false)=>{const t=musicRef.current;if(!t)return;t.pause();if(r)t.currentTime=0}; const startMusic=async(force=false)=>{if((!sound&&!force)||!musicRef.current)return;musicRef.current.volume=volume;try{await musicRef.current.play()}catch{}};
  const beginCard=(w:string)=>{setSelected(w);setDragging(w);setFeedback(`Find the envelope for “${w}”`);playSound("paper")};
  const tryMatch=(target:string,source=dragging??selected)=>{if(!source||matched.includes(source))return;const expected=PAIRS.find(([a])=>a===source)?.[1];if(expected===target){const nm=[...matched,source],ns=streak+1;setMatched(nm);setStreak(ns);setBestStreak(Math.max(bestStreak,ns));setSelected(null);setDragging(null);setFeedback(ns>=3?`${ns} perfect deliveries in a row!`:"Perfect delivery — sealed with care.");playSound("seal");if(nm.length===PAIRS.length)setTimeout(()=>{stopMusic();setScreen("finish");playSound("finish")},850);else if(activeCards.every(w=>nm.includes(w))){setFeedback("Mailbag complete — bringing the next letters...");setTimeout(()=>{setBatchIndex(n=>n+1);setFeedback("Pick up a Polaroid and find its opposite envelope")},650)}}else{setWrongEnvelope(target);setStreak(0);setFeedback("Wrong address — that Polaroid is coming back.");playSound("wrong");setTimeout(()=>{setWrongEnvelope(null);setSelected(null);setDragging(null);setFeedback("Pick up a Polaroid and find its opposite envelope")},750)}};
  const reset=()=>{playSound("click");stopMusic(true);setRound(n=>n+1);setBatchIndex(0);setSelected(null);setDragging(null);setMatched([]);setStreak(0);setBestStreak(0);setFeedback("Pick up a Polaroid and find its opposite envelope");setScreen("start")};
  return <main className={`site-shell screen-${screen} ${dragging?"is-dragging":""}`} onPointerMove={e=>setThread(c=>c?{...c,cursorX:e.clientX+5,cursorY:e.clientY+7}:null)}><div className="grain"/>{thread&&<svg className="quill-thread" aria-hidden="true"><path d={`M ${thread.cursorX} ${thread.cursorY} Q ${(thread.cursorX+thread.targetX)/2} ${Math.min(thread.cursorY,thread.targetY)-34} ${thread.targetX} ${thread.targetY}`}/><circle cx={thread.targetX} cy={thread.targetY} r="3"/></svg>}<audio ref={musicRef} src={asset("/pressed-ferns.mp3")} loop preload="metadata"/><div className="audio-controls"><button className="sound-btn" onClick={()=>{const p=Boolean(musicRef.current&&!musicRef.current.paused);if(sound&&p){playSound("click");stopMusic();setSound(false)}else{setSound(true);void startMusic(true)}}}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><label className="volume-control"><input type="range" min="0" max="1" step=".01" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);if(musicRef.current)musicRef.current.volume=v;if(v>0&&!sound){setSound(true);void startMusic(true)}}}/></label></div>
  {screen==="start"&&<section className="start-letter enter"><div className="start-props" aria-hidden="true"><div className="start-polaroid"><img src={photoFor("confident")} alt=""/><span>confident</span></div><img className="start-envelope" src={asset("/envelope-fern-closed-opt.webp")} alt=""/><img className="start-quill" src={asset("/quill-cursor.png")} alt=""/></div><div className="wax-seal">A</div><p className="eyebrow">The Academy Mailroom · Special Delivery</p><h1>Match the<br/><em>opposites</em></h1><div className="rule"/><p className="intro">Deliver every Polaroid to the envelope<br/>marked with its opposite adjective.</p><div className="preview-mail" aria-hidden="true"><div className="mini-photo">confident</div><span>→</span><div className="mini-envelope">shy</div></div><button className="primary-btn" onClick={()=>{playSound("click");void startMusic();setScreen("game")}}>Open the mailroom <span>→</span></button><p className="tiny-note">14 deliveries · no timer · take your time</p></section>}
  {screen==="game"&&<section className="mailroom enter"><header className="game-header"><div><h2>Match the opposites</h2><p>Drag a Polaroid into its opposite envelope.</p></div></header><div className="counter"><strong>{matched.length}</strong><span>/ {PAIRS.length} pairs</span><i><b style={{width:`${matched.length/PAIRS.length*100}%`}}/></i><Sparkles size={22}/></div><div className="desk-layout"><section className="polaroid-tray"><div className="polaroid-grid">{activeCards.map((word,i)=>{const sent=matched.includes(word);return <button key={word} draggable={!sent} onDragStart={e=>{e.dataTransfer.setData("text/plain",word);beginCard(word)}} onDragEnd={()=>setDragging(null)} onClick={()=>{if(!sent)beginCard(word)}} disabled={sent} className={`polaroid angle-${i%4} ${selected===word?"selected":""} ${sent?"sent":""}`}><span className="photo-window"><img src={photoFor(word)} alt="" draggable={false} loading="eager"/><i>{String(batchIndex*4+i+1).padStart(2,"0")}</i></span><strong>{word}</strong></button>})}</div></section><section className="envelope-tray"><div className="envelope-grid">{activeEnvelopes.map((word,i)=>{const source=PAIRS.find(([,b])=>b===word)?.[0]??"",sealed=matched.includes(source);return <button key={word} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();tryMatch(word,e.dataTransfer.getData("text/plain"))}} onClick={()=>tryMatch(word)} onPointerEnter={e=>{if(sealed)return;const r=e.currentTarget.getBoundingClientRect();setThread({cursorX:e.clientX+5,cursorY:e.clientY+7,targetX:r.left+r.width/2,targetY:r.top+r.height*.68})}} onPointerLeave={()=>setThread(null)} disabled={sealed} className={`envelope angle-${(i+2)%4} ${selected?"ready":""} ${wrongEnvelope===word?"wrong":""} ${sealed?"sealed":""}`}><span className="envelope-art"><img className="envelope-closed" src={asset("/envelope-fern-closed-opt.webp")} alt=""/><img className="envelope-open" src={asset("/envelope-fern-open-opt.webp")} alt=""/></span><span className="envelope-word">{word}</span>{sealed&&<span className="seal-mark">✓</span>}</button>})}</div></section><aside className="garden-card"><div className="plant-stage"><img key={growthStage} src={asset(`/growth-stages/stage-${growthStage}.webp`)} alt="plant" className="growing-plant growth-stage-image"/>{matched.length===1&&<img src={asset("/growth-stages/seed.webp")} alt="" className="falling-seed"/>}{streak>=3&&<Sparkles className="sparkle" size={26}/>}</div></aside></div><div className="feedback-plaque"><span>{feedback}</span><small>{streak>1?`✦ ${streak} in a row`:"Special delivery"}</small></div></section>}
  {screen==="finish"&&<section className="finish-letter enter"><div className="finish-plant"><img src={asset("/growth-stages/stage-7.webp")} alt="A fully grown potted peony"/></div><p className="eyebrow">All fourteen letters delivered</p><h1>Perfectly<br/><em>addressed!</em></h1><p className="intro">Every opposite found. Every envelope sealed.</p><button className="primary-btn" onClick={reset}><RotateCcw size={17}/> Play again</button></section>}</main>;
}
